name: adonis-inertia-starter

services:
  postgres:
    image: postgres:17.4
    container_name: adonis-inertia-starter-postgres
    environment:
      POSTGRES_DB: adonis-sample-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - adonis-inertia-starter_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  adonis-inertia-starter_postgres_data:
